config/routes.rb
Rails.application.routes.draw do
  root "top#index"
  devise_for :users, controllers: { registrations: 'users/registrations'}
  devise_scope :user do
    post "/users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  resources :rooms, only: [:new, :create, :show, :destroy] do
    resources :talks, only: [:create, :destroy]
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :talks, dependent: :destroy
  validates :title, presence: true, length: {in: 1..150}

  def self.search(search)
    if search
      where(['title LIKE ?', "%#{search}%"])
    else
      all
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :destroy]

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to root_url
    else
      render "new"
    end
  end

  def show
    @talk = Talk.new
  end

  def destroy
    if @room.destroy
      redirect_to root_url
    else
      render :show
    end
  end

  private
    def room_params
      params.require(:room).permit(:title).merge(user_id: current_user.id)
    end

    def set_room
      @room = Room.find_by(id: params[:id])
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/new.html.erb
<div class="row">
  <div class="col-md-6 offset-md-3">
    <h1 class="text-center mt-5">ルーム作成</h1>

    <div class="mt-4">
      <%= form_with(model: @room, local: true) do |f| %>
        <% if @room.errors.any? %>
          <p class="text-danger">タイトルは1~150文字にしてください。</p>
        <% end %>
        <div>
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="mt-2">
          <%= f.submit "作成する", class: "btn btn-primary form-control" %>
        </div>
      <% end %>
    </div>
  </div>  
</div>

app/views/rooms/show.html.erb
<div class="row">
  <div class="col-md-6 offset-md-3">
    <div class="row">
      <h1 class="col-9 text-center mt-5"><%= @room.title %></h1>
      <div class="col-3">
        <%= link_to "削除", @room, method: :delete, data: {confirm: "本当によろしいですか？"}, class: "btn btn-danger btn-sm mt-5" if @room.user == current_user %>
      </div>
    </div>

    <div>
      <%= form_with(model: [@talk], url: room_talks_path(@room), local: true) do |f| %>
        <%= f.hidden_field :room_id, value: @room.id %>
        <% if f.object.errors.any? %>
          <p class="text-danger">1~150文字にしてください。</p>
        <% end %>

        <div>
          <div>
            <%= f.text_area :title, class: "form-control", placeholder: "投稿内容" %>
          </div>
          <div class="d-grid gap-2 d-md-flex d-md-block justify-content-md-end">
            <%= f.submit "投稿", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>  
    </div>

    <div class="mt-3">
      <% @room.talks.each do |talk| %> 
        <div class="row">
          <div class="col-9 border-bottom mt-2">
            <div class="mt-1">
              <div class=""><%= talk.id %>: <%= talk.title %></div>
              <div class="small text-end"><%= talk.user.name %>: <%= talk.created_at.to_s(:datetime_jp) %></div>
            </div>
          </div>
          <div class="col-3">
            <%= link_to "削除", room_talk_path(@room, talk), method: :delete, class: "btn btn-danger btn-sm mt-3", data: {confirm: "削除しても大丈夫ですか？"} if talk.user == current_user %>
          </div>
        </div>
      <% end %>
    </div>
  </div> 
</div>